"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { ArrowLeft, Zap } from "lucide-react";
import Badge from "@/components/shared/Badge";
import SectionHeader from "@/components/shared/SectionHeader";
import { createClient } from "@/lib/supabase/client";
import type { ContentStatus, ContentType } from "@/lib/database.types";

const STATUS_FLOW: ContentStatus[] = [
  "idea",
  "draft",
  "review",
  "approved",
  "scheduled",
  "published",
];

interface ContentItem {
  id: string;
  title: string | null;
  body: string | null;
  type: ContentType;
  status: ContentStatus;
  topic_tags: string[] | null;
  scheduled_for: string | null;
  published_url: string | null;
  source: string;
  updated_at: string;
  team_members: { full_name: string } | null;
}

export default function ContentDetailView({
  item,
}: {
  item: ContentItem;
}) {
  const router = useRouter();
  const [editing, setEditing] = useState(false);
  const [body, setBody] = useState(item.body ?? "");
  const [title, setTitle] = useState(item.title ?? "");
  const [saving, setSaving] = useState(false);

  const isAgent =
    item.source === "content_agent" || item.source === "coordinator_agent";

  const handleStatusChange = async (newStatus: ContentStatus) => {
    const supabase = createClient();
    const update: Record<string, unknown> = { status: newStatus };
    if (newStatus === "published") {
      update.published_at = new Date().toISOString();
    }
    await supabase.from("content_items").update(update).eq("id", item.id);
    router.refresh();
  };

  const handleSave = async () => {
    setSaving(true);
    const supabase = createClient();
    await supabase
      .from("content_items")
      .update({ title, body })
      .eq("id", item.id);
    setSaving(false);
    setEditing(false);
    router.refresh();
  };

  const handleAssignToAgent = async () => {
    const supabase = createClient();
    await supabase.from("agent_activity").insert({
      agent_name: "content",
      action: "generate",
      status: "pending",
      trigger_type: "manual",
      trigger_ref: item.id,
      proposed_actions: [],
    });
    router.refresh();
  };

  return (
    <div className="py-4 space-y-5">
      <Link
        href="/content"
        className="flex items-center gap-1 font-mono text-[10px] text-[--text-dim] hover:text-[--text] transition-colors"
      >
        <ArrowLeft size={12} />
        Back
      </Link>

      {/* Header */}
      <div className="space-y-2">
        <div className="flex items-center gap-2">
          <Badge variant="default">{item.type}</Badge>
          {isAgent && (
            <span className="flex items-center gap-0.5 font-mono text-[9px] text-[--accent]">
              <Zap size={10} />
              Generated by Agent
            </span>
          )}
        </div>

        {editing ? (
          <input
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            className="w-full bg-[--bg] border border-[--border-2] rounded px-3 py-2 text-base text-[--text] focus:border-[--accent] outline-none"
          />
        ) : (
          <h1
            className="text-base font-medium text-[--text] cursor-pointer hover:text-[--accent] transition-colors"
            onClick={() => setEditing(true)}
          >
            {item.title || "Untitled"}
          </h1>
        )}

        {/* Status Selector */}
        <div className="flex items-center gap-1 flex-wrap">
          {STATUS_FLOW.map((s) => (
            <button
              key={s}
              onClick={() => handleStatusChange(s)}
              className={`font-mono text-[8px] uppercase tracking-wider px-2 py-1 rounded-[3px] transition-colors ${
                item.status === s
                  ? "bg-[--accent] text-black"
                  : "bg-[--surface-2] text-[--text-muted] hover:text-[--text-dim]"
              }`}
            >
              {s}
            </button>
          ))}
        </div>

        {/* Tags */}
        {item.topic_tags && item.topic_tags.length > 0 && (
          <div className="flex flex-wrap gap-1">
            {item.topic_tags.map((tag) => (
              <Badge key={tag} variant="default">
                {tag}
              </Badge>
            ))}
          </div>
        )}
      </div>

      {/* Body */}
      <section>
        <div className="flex items-center justify-between mb-2">
          <SectionHeader>Content</SectionHeader>
          <button
            onClick={() => setEditing(!editing)}
            className="font-mono text-[9px] text-[--text-dim] hover:text-[--accent] transition-colors"
          >
            {editing ? "Preview" : "Edit"}
          </button>
        </div>

        {editing ? (
          <div className="space-y-2">
            <textarea
              value={body}
              onChange={(e) => setBody(e.target.value)}
              rows={12}
              className="w-full bg-[--bg] border border-[--border-2] rounded px-3 py-2 font-mono text-xs text-[--text] focus:border-[--accent] outline-none resize-y"
            />
            <button
              onClick={handleSave}
              disabled={saving}
              className="font-mono text-[10px] uppercase tracking-wider px-4 py-2 rounded-[4px] bg-[--accent] text-black hover:opacity-90 transition-opacity disabled:opacity-50"
            >
              {saving ? "Saving..." : "Save"}
            </button>
          </div>
        ) : (
          <div className="bg-[--surface] border border-[--border] rounded-[6px] p-3">
            {item.body ? (
              <div className="prose prose-invert prose-xs max-w-none text-xs text-[--text-dim] whitespace-pre-wrap">
                {item.body}
              </div>
            ) : (
              <p className="text-xs text-[--text-muted] italic">
                No content yet. Click Edit to start writing.
              </p>
            )}
          </div>
        )}
      </section>

      {/* Scheduling */}
      {item.scheduled_for && (
        <div>
          <SectionHeader className="mb-1">Scheduled For</SectionHeader>
          <span className="font-mono text-xs text-[--text-dim]">
            {new Date(item.scheduled_for).toLocaleString()}
          </span>
        </div>
      )}

      {item.published_url && (
        <div>
          <SectionHeader className="mb-1">Published URL</SectionHeader>
          <a
            href={item.published_url}
            target="_blank"
            rel="noopener noreferrer"
            className="font-mono text-xs text-[--accent] hover:underline"
          >
            {item.published_url}
          </a>
        </div>
      )}

      {/* Assign to Agent */}
      <button
        onClick={handleAssignToAgent}
        className="flex items-center gap-1.5 font-mono text-[10px] uppercase tracking-wider px-3 py-2 rounded-[4px] border border-[--border] text-[--text-dim] hover:border-[--accent] hover:text-[--accent] transition-colors"
      >
        <Zap size={12} />
        Assign to Agent
      </button>
    </div>
  );
}
